# Generated by Django 5.1.6 on 2025-02-10 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название команды')),
                ('city', models.CharField(max_length=255, verbose_name='Город/Регион')),
                ('institution', models.CharField(max_length=255, verbose_name='Учебное заведение')),
                ('contact_info', models.TextField(verbose_name='Контактная информация')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Краткое описание проекта')),
                ('technical_specs', models.TextField(blank=True, null=True, verbose_name='Технические характеристики')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='application_form.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('role', models.CharField(max_length=255, verbose_name='Роль в команде')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='application_form.team')),
            ],
        ),
    ]
