# Generated by Django 5.1.3 on 2025-03-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=50, verbose_name='Telegram Chat ID')),
                ('bot_token', models.CharField(max_length=100, verbose_name='Telegram Bot Token')),
            ],
            options={
                'verbose_name': 'Настройки бота',
                'verbose_name_plural': 'Настройки бота',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
