# Generated by Django 5.1.3 on 2025-03-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_form', '0002_botsettings_team_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='video_url',
        ),
        migrations.AddField(
            model_name='team',
            name='video',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
