# Generated by Django 5.1.3 on 2025-03-03 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_form', '0003_remove_team_video_url_team_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botsettings',
            name='bot_token',
        ),
    ]
