# Generated by Django 5.1.3 on 2025-03-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_form', '0004_remove_botsettings_bot_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
