# Generated by Django 5.1.3 on 2025-03-05 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_form', '0006_uploadedfile_delete_botsettings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='file',
            new_name='video',
        ),
    ]
