# Generated by Django 5.1.3 on 2025-03-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_form', '0007_rename_file_team_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='video',
        ),
        migrations.AddField(
            model_name='team',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
